name: deploy-workflow
on: [push]
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out repo
        uses: actions/checkout@v2 # checks out repo 
      - name: Enable access to npm commands
        id: setup-node
        uses: actions/setup-node@v2 # enable access to npm 
        with:
          node-version: '12'
          # cache: 'npm' # https://github.com/actions/setup-node#caching-packages-dependencies
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm install
      # - name: Cache source files # https://nextjs.org/docs/messages/no-cache#github-actions
      #   id: cache
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ github.workspace }}/.next/cache
      #     # Generate a new cache whenever packages or source files change.
      #     key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]sx?') }}
      #     # If source files changed but packages didn't, rebuild from a prior cache.
      #     restore-keys: |
      #       ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      # - run: npm run build