name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checks out repo
      - uses: actions/setup-node@v2 # enable access to npm 
        with:
          node-version: '12'
      - name: Cache packages and source files
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]sx?') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Install packages (when changed or no cache)
        if: steps.cache.outputs.cache-hit != 'true' # if no/stale cache
        run: npm install
      - run: npm run build